version: '3'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
